vim.g.mapleader = " "
vim.g.maplocalleader = " "
--vim.opt.clipboard = ""
vim.o.termguicolors = true
vim.g.have_nerd_font = true
-- vim.opt.number = true
-- vim.opt.relativenumber = true
vim.opt.signcolumn = "yes"
vim.opt.number = false
vim.opt.relativenumber = false
vim.opt.mouse = "a"
vim.opt.showmode = false
vim.opt.breakindent = true
vim.opt.undofile = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.updatetime = 250
vim.opt.timeoutlen = 300
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.list = true
vim.opt.listchars = { tab = "» ", trail = "·", nbsp = "␣" }
vim.opt.inccommand = "split"
vim.opt.cursorline = true
vim.opt.scrolloff = 20
vim.opt.confirm = true
vim.cmd("let g:netrw_liststyle = 3")
vim.opt.autoindent = true
vim.opt.backspace = "indent,eol,start"
vim.opt.swapfile = false
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.winborder = "rounded"

